import { Invoice, Transaction, User } from "@/types";

export const MOCK_USER: User = {
  id: "user_1",
  name: "Ada Okafor",
  email: "ada@example.com",
  role: "freelancer",
  kycStatus: "approved",
  walletBalance: 4250.0,
};

export const MOCK_INVOICES: Invoice[] = [
  {
    id: "inv_001",
    clientName: "Techwave Ltd",
    clientEmail: "billing@techwave.io",
    amount: 1500,
    currency: "USD",
    dueDate: "2025-04-15",
    description: "UI/UX Design — March",
    status: "paid",
    createdAt: "2025-03-01",
    userId: "user_1",
  },
  {
    id: "inv_002",
    clientName: "Brandify Agency",
    clientEmail: "pay@brandify.co",
    amount: 800,
    currency: "USD",
    dueDate: "2025-04-20",
    description: "Logo & Brand Identity",
    status: "pending",
    createdAt: "2025-03-10",
    userId: "user_1",
  },
  {
    id: "inv_003",
    clientName: "Nova Startups",
    clientEmail: "finance@novastartups.com",
    amount: 2200,
    currency: "USD",
    dueDate: "2025-03-28",
    description: "Frontend Development",
    status: "overdue",
    createdAt: "2025-02-28",
    userId: "user_1",
  },
  {
    id: "inv_004",
    clientName: "GreenLeaf Co",
    clientEmail: "accounts@greenleaf.com",
    amount: 650,
    currency: "USD",
    dueDate: "2025-05-01",
    description: "Social Media Design",
    status: "pending",
    createdAt: "2025-03-20",
    userId: "user_1",
  },
  {
    id: "inv_005",
    clientName: "Orbit Media",
    clientEmail: "billing@orbitmedia.ng",
    amount: 3100,
    currency: "USD",
    dueDate: "2025-04-30",
    description: "Web App — Phase 1",
    status: "paid",
    createdAt: "2025-03-15",
    userId: "user_1",
  },
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: "txn_001",
    type: "credit",
    amount: 1500,
    status: "completed",
    description: "Payment from Techwave Ltd",
    createdAt: "2025-03-05",
    userId: "user_1",
  },
  {
    id: "txn_002",
    type: "credit",
    amount: 3100,
    status: "completed",
    description: "Payment from Orbit Media",
    createdAt: "2025-03-18",
    userId: "user_1",
  },
  {
    id: "txn_003",
    type: "debit",
    amount: 250,
    status: "completed",
    description: "Withdrawal to bank account",
    createdAt: "2025-03-20",
    userId: "user_1",
  },
  {
    id: "txn_004",
    type: "credit",
    amount: 800,
    status: "pending",
    description: "Payment from Brandify Agency",
    createdAt: "2025-03-22",
    userId: "user_1",
  },
  {
    id: "txn_005",
    type: "debit",
    amount: 100,
    status: "failed",
    description: "Withdrawal to bank account",
    createdAt: "2025-03-25",
    userId: "user_1",
  },
];

export const MOCK_ALL_USERS = [
  {
    id: "user_1",
    name: "Ada Okafor",
    email: "ada@example.com",
    role: "freelancer" as const,
    kycStatus: "approved" as const,
    walletBalance: 4250.0,
  },
  {
    id: "user_2",
    name: "Emeka Nwosu",
    email: "emeka@example.com",
    role: "freelancer" as const,
    kycStatus: "pending" as const,
    walletBalance: 800.0,
  },
  {
    id: "user_3",
    name: "Zara Ahmed",
    email: "zara@example.com",
    role: "freelancer" as const,
    kycStatus: "pending" as const,
    walletBalance: 0,
  },
  {
    id: "user_4",
    name: "Tunde Bello",
    email: "tunde@example.com",
    role: "freelancer" as const,
    kycStatus: "rejected" as const,
    walletBalance: 1200.0,
  },
];
